name: 'Locust Load Test'
author: 'Vipin Kumar'
description: 'Load Test an application using Locust'
inputs:
  LOCUSTFILE:
    description: 'The locustfile you want to use to load test. If no file is provided, a simple load test will be done on the landing page of the provided URL.'
    required: false
  URL:
    description: 'URL to the site you want to load test. This is Required!'
    required: true
  USERS:
    description: 'Number of Users to spawn.'
    required: false
    default: " "
  RATE:
    description: 'Specify the hatch rate (number of users to spawn per second).'
    required: false
    default: " "
  RUNTIME:
    description: 'Specify the run time for a test.'
    required: false
    default: " "
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.LOCUSTFILE }}
    - ${{ inputs.URL }}
    - ${{ inputs.USERS }}
    - ${{ inputs.RATE }}
    - ${{ inputs.RUNTIME }}
branding:
  icon: 'link'
  color: 'green'