name: Test Locust Load Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipinkumar1234/Locust-load-GHA@master
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://google.com"
          USERS: "6"
          RATE: "6"
          RUNTIME: "10s"